In [5]:
import matplotlib.pyplot as plt
import numpy as np
import datetime
import matplotlib.dates as mdates
from matplotlib.ticker import AutoMinorLocator
import pandas as pd

In [38]:
MockData = pd.read_csv("data/NZCF_MOCK_DATA.csv")

In [39]:
MockData.head()

,Tree ID,Location Latitude,Location Longitude,Tree Type,Age,Gender,Fruiting,Disease,Last Updated,Planted,Row Number,Planted By,Location Elevation,Daily Check
0,0c1194f4-df24-46ae-8218-65d7614360ef,17.712720,121.442447,Ranunculaceae,85.0,Genderqueer,True,False,06/09/2021,04/05/2009,1,Feodora Neumann,43.967680,16:54
1,e8d32f63-6e88-4e5d-961f-b356640a3477,16.858360,43.197810,Arthoniaceae,18.0,Male,True,True,02/12/2020,29/12/1981,2,Zak Cowgill,30.134451,NaN
2,be4db5e5-d4f8-416e-89e5-33b2d16344bd,32.809026,110.112629,Liliaceae,6.0,Female,True,False,22/03/2021,19/01/1942,3,Theresina Pinshon,51.232987,14:35
3,913ce225-62e5-4ada-9e72-f02c939927ad,-7.263553,106.823451,Crocyniaceae,47.0,Genderfluid,True,False,18/10/2021,31/01/1973,4,Lyon Van Der Walt,51.221186,18:42
4,8c08f1fd-66b9-44b6-90e8-06473054d608,53.398308,20.946111,Fabaceae,32.0,Male,True,True,NaN,NaN,5,Deck Bonevant,NaN,12:32

In [40]:
print(MockData.dtypes)

Tree ID                object
Location Latitude     float64
Location Longitude    float64
Tree Type              object
Age                   float64
Gender                 object
Fruiting                 bool
Disease                  bool
Last Updated           object
Planted                object
Row Number              int64
Planted By             object
Location Elevation    float64
Daily Check            object
dtype: object

In [15]:
#MockData['Planted'] = pd.to_datetime(MockData['Planted'])
MockData['Planted'] = pd.to_datetime(MockData['Planted'], format = "%d-%m-%Y").dt.strftime('%Y-%m-%d') # did not work due to null values, which would need to be removed first.

ValueError: time data '2009-04-05' does not match format '%d-%m-%Y' (match)

In [45]:
MockData['Planted']=MockData['Planted'].astype('datetime64[ns]') #accounts for null values in date
MockData["Last Updated"]=MockData["Last Updated"].astype('string')
MockData["Daily Check"]=MockData["Daily Check"].astype('string')
MockData["Tree ID"] = MockData["Tree ID"].astype('string')
MockData["Age"] = MockData["Age"].astype('Int64')
MockData["Tree Type"] = MockData["Tree Type"].astype('string')
MockData["Gender"] = MockData["Gender"].astype('string')
MockData["Planted By"] = MockData["Planted By"].astype('string')

In [55]:
MockData["UpdateTime"] = MockData["Last Updated"] + '-' + MockData["Daily Check"]
MockData["UpdateTime"] = MockData["UpdateTime"].astype('datetime64[ns]')

ValueError: Error parsing datetime string "2021-06-09-16:54" at position 10

In [52]:
MockData.head()
#print(MockData.dtypes)

,Tree ID,Location Latitude,Location Longitude,Tree Type,Age,Gender,Fruiting,Disease,Last Updated,Planted,Row Number,Planted By,Location Elevation,Daily Check,UpdateTime
0,0c1194f4-df24-46ae-8218-65d7614360ef,17.712720,121.442447,Ranunculaceae,85,Genderqueer,True,False,2021-06-09,2009-04-05,1,Feodora Neumann,43.967680,16:54,2021-06-09-16:54
1,e8d32f63-6e88-4e5d-961f-b356640a3477,16.858360,43.197810,Arthoniaceae,18,Male,True,True,2020-02-12,1981-12-29,2,Zak Cowgill,30.134451,<NA>,<NA>
2,be4db5e5-d4f8-416e-89e5-33b2d16344bd,32.809026,110.112629,Liliaceae,6,Female,True,False,2021-03-22,1942-01-19,3,Theresina Pinshon,51.232987,14:35,2021-03-22-14:35
3,913ce225-62e5-4ada-9e72-f02c939927ad,-7.263553,106.823451,Crocyniaceae,47,Genderfluid,True,False,2021-10-18,1973-01-31,4,Lyon Van Der Walt,51.221186,18:42,2021-10-18-18:42
4,8c08f1fd-66b9-44b6-90e8-06473054d608,53.398308,20.946111,Fabaceae,32,Male,True,True,<NA>,NaT,5,Deck Bonevant,NaN,12:32,<NA>

Tree ID                       string
Location Latitude            float64
Location Longitude           float64
Tree Type                     object
Age                            Int64
Gender                        object
Fruiting                        bool
Disease                         bool
Last Updated                  object
Planted                       object
Row Number                     int64
Planted By                    object
Location Elevation           float64
Daily Check                   object
PlantedAdjust         datetime64[ns]
dtype: object